### PR TITLE
Add citation request to acknowledgment statement

### PR DESCRIPTION
**Pull request by PatCapon39**
Please check the code is correct for the paragraphs, the italics of the journal name and the hyperlinked doi

### CODE REVIEW

**Comment by PatCapon39** [comment]
@neoformit bracket fix is here, plus adding a request to cite the Galaxy paper that @GarethPrice-Aus and I discussed yesterday. Cheers!

**Comment by PatCapon39** [comment]
Looks great, nice one! Thanks for fixing the syntax too. My nitpicky comment would be that there's a rather large gap between "its use with the following statement:" and then the section in italics, so if we can make that gap match the rest of the line spacing that would be ideal

**Comment by neoformit** [comment]
How's that?

image

**Comment by PatCapon39** [comment]
Nicely done! Thanks Cam :)

**Pull request merged**
